    version: '3.8'
    services:
      linkedin-agent-app:
        image: linkedin-agent-app:latest
        environment:
          unipile_dsn: ${unipile_dsn}
          unipile_access_token: ${unipile_access_token}
          db_host: db
          db_user: ${db_user}
          db_password: ${db_password}
          db_name: ${db_name}
          port: 8080
        ports:
          - "8080:8080"
        depends_on:
          - ngrok
          - db
          - adminer
          
      ngrok:
        image: ngrok/ngrok:alpine
        environment:
          NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
        command: "http linkedin-agent-app:8080 --url=furless-irrefrangibly-rashida.ngrok-free.dev"
        ports:
          - "4040:4040" # For ngrok's local web interface (optional)

      db:
        image: mariadb
        restart: always
        environment:
          MARIADB_ROOT_PASSWORD: ${db_password}
          MARIADB_DATABASE: ${db_name}

      adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080